(async()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>v==null?'Not configured':Number(v).toLocaleString(undefined,{maximumFractionDigits:2}),money=v=>v==null?'Not configured':'฿'+num(v),badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`;
const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th${h[1]?' class="secondary"':''}>${esc(h[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td${heads[i]?.[1]?' class="secondary"':''}>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
try{const config=await fetch('./rules_config.json').then(r=>{if(!r.ok)throw Error('Rules could not load');return r.json()}),payments=await fetch('./payments.json').then(r=>{if(!r.ok)throw Error('Payment records could not load');return r.json()}),d=window.FPL_DASHBOARD_DATA;
if(!d||d.status!=='ok')throw Error(d?.error||'Snapshot unavailable. Run python3 fpl_dashboard_updater.py');
const a=FPLEngine.build(d,config,payments);window.dashboardAnalytics=a;document.title=a.c.name+' • FPL';$('brand').textContent=a.c.name;
const age=(Date.now()-Date.parse(a.updated))/86400000;if(age>7)a.warnings.push(`Snapshot is ${Math.floor(age)} days old; run the manual updater.`);
a.warnings.push(`League identity check: repository uses ID ${a.c.id}; earlier project notes listed the leagues in reverse. Confirm before changing IDs.`);
$('meta').textContent=`${a.c.season} · Latest API snapshot GW${a.latest} · League ${a.c.id} · Updated ${new Date(a.updated).toLocaleString()} · ${a.warnings.length?'DATA WARNING':'Snapshot loaded'}`;
$('warnings').innerHTML=a.warnings.length?`<details class="warning" open><summary>DATA WARNING • ${a.warnings.length} checks need attention</summary>${a.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</details>`:'';
$('main').hidden=false;
const paid=a.money.reduce((s,m)=>s+m.paid,0),assessed=a.money.reduce((s,m)=>s+m.assessed,0);
$('snapshot').innerHTML=a.managers.slice(0,3).map(m=>`<article class="panel"><div class="ranklabel">${m.rank===1?'🏆':m.rank===2?'🥈':'🥉'} PLACE ${m.rank} ${m.move==null?'':m.move>0?'↑ '+m.move:m.move<0?'↓ '+Math.abs(m.move):'→'}</div><div class="name">${esc(m.name)}</div><small>${esc(m.team)}</small><div class="big">${num(m.total)} <small>pts</small></div><small>GW${a.latest} · ${num(m.gw)} raw pts</small></article>`).join('')+`<article class="panel"><div class="ranklabel">PRIZE POOL • RECORDED FUNDING</div><div class="big">${money(paid)}</div><progress value="${Math.min(paid,a.c.target)}" max="${a.c.target}" aria-label="Prize pool funding"></progress><p>${num(paid/a.c.target*100)}% of ${money(a.c.target)}</p><small>Verified assessed: ${money(assessed)}<br>Historical payments: ${payments.penalties.length?'Recorded':'Not recorded'}</small></article>`;
const current=a.periods.findIndex(p=>p.year===new Date().getFullYear()&&p.month===new Date().toLocaleString('en',{month:'short'}));
$('month').innerHTML=a.periods.map((p,i)=>`<option value="${i}">${esc(p.month)} ${p.year}</option>`).join('');$('month').value=current>=0?current:Math.max(0,a.periods.findIndex(p=>p.start_gw<=a.latest&&p.end_gw>=a.latest));
function renderMonth(){const p=a.periods[+$('month').value],top=p.rows[0]?.points;const status=r=>r.amount>0?'PENALTY':p.rows.filter(x=>x.points<r.points).length<=p.penalty_teams?'WATCH':'SAFE';
$('monthmeta').textContent=`${p.month} ${p.year} · GW${p.start_gw}–${p.end_gw} · ${p.penalty_teams??'Not configured'} penalty slots`;
$('monthly').innerHTML=p.rows.length?table([['Rank'],['Manager'],['Raw',1],['Hits',1],['Adjusted'],['Gap',1],['Status']],p.rows.map((r,i)=>[num(1+p.rows.filter(x=>x.points>r.points).length),`<b>${esc(r.name)}</b><small>${esc(r.team)}</small><div class="mini"><details><summary>Score & penalty details</summary>Raw ${num(r.raw)} · hits ${num(r.hits)} · gap ${num(top-r.points)}<br>Penalty ${money(r.amount)} · slots ${esc(r.positions)}${r.tied?' · shared tie':''}</details></div>`,num(r.raw),num(r.hits),`<b>${num(r.points)}</b>`,num(top-r.points),badge(status(r))])):`<div class="panel">${p.status==='Not started'?'This month has not started in the saved snapshot.':'Complete monthly data is unavailable. Calculation withheld.'}</div>`;
$('monthsummary').innerHTML=`<h3>${esc(p.month)} command center</h3><p>${badge(p.status)}</p><div class="big">${money(p.penalty_pool_thb)}</div><small>Configured monthly penalty pool</small><p>Monthly leader: <b>${p.rows.length?esc(p.rows.filter(r=>r.points===top).map(r=>r.name).join(', ')):'Awaiting data'}</b></p><p>Penalty zone: ${p.rows.filter(r=>r.amount>0).map(r=>esc(r.name)+' '+money(r.amount)).join(' · ')||'Awaiting data'}</p><p>${p.penalty_teams} slots may include more managers when points tie.</p>`;}
$('month').onchange=renderMonth;renderMonth();
$('prizecards').innerHTML=a.prizes.map((p,i)=>`<article class="prize"><div class="ranklabel">PRIZE ${i+1} • ${esc(p.label)}</div><div class="name">${p.winner?esc(p.winner.name):esc(p.status)}</div><p>${p.winner?num(p.metric==='season_rank'?-p.stat:p.stat)+(p.metric==='season_rank'?' (league rank)':p.metric==='team_value'?' £m':''):'Awaiting eligible winner'}</p><h3>${money(p.amount_thb)} · ${num(p.percent)}%</h3><p>${badge(p.status)}</p><small>${esc(p.reason)}</small></article>`).join('');
$('allocations').innerHTML=table([['Category'],['Allocation'],['Current eligible winner'],['Projected amount']],a.prizes.map(p=>[esc(p.label),num(p.percent)+'%',esc(p.winner?.name||p.status),money(p.amount_thb)]));
$('tracker').innerHTML=a.periods.map((p,i)=>`<details><summary>${esc(p.month)} ${p.year} · GW${p.start_gw}–${p.end_gw} · ${p.penalty_teams} slots · ${money(p.penalty_pool_thb)} · ${esc(p.status)}</summary><p>Payment status: ${p.status==='Finalized'?'See recorded payments below':'Awaiting verification / finalization'}</p>${p.rows.length?table([['Manager'],['Raw',1],['Hits',1],['Adjusted'],['Slot',1],['Penalty'],['Paid',1]],p.rows.filter(r=>r.amount>0).map(r=>[esc(r.name),num(r.raw),num(r.hits),num(r.points),esc(r.positions),money(r.amount),money(payments.penalties.filter(x=>x.manager_id===r.id&&x.month===p.month&&x.year===p.year).reduce((s,x)=>s+x.amount_thb,0))])):'<p>Complete breakdown is unavailable in this snapshot.</p>'}</details>`).join('');
$('money').innerHTML=table([['Manager'],['Prize won',1],['Paid',1],['Outstanding'],['Projected prize',1],['Net paid position',1]],a.money.map(m=>[`<b>${esc(m.name)}</b><div class="mini"><details><summary>Financial details</summary>Prize won ${money(m.won)} · paid ${money(m.paid)}<br>Projected prize ${money(m.projected)} · net ${money(m.net)}</details></div>`,money(m.won),money(m.paid),a.periods.some(p=>p.status==='Unverified snapshot')?'Unverified':money(m.outstanding),money(m.projected),money(m.net)]));
$('analytics').innerHTML=a.money.map(m=>`<details><summary>#${m.rank} ${esc(m.name)} · ${num(m.total)} pts</summary><p>${esc(m.team)}</p><div class="stats">${[['Latest GW',num(m.gw)],['Transfer hit',num(m.hit)],['Captain total',num(m.captain)],['MVP wins',num(m.mvp)],['Best GW',num(m.best)],['Team value','£'+num(m.value)+'m'],['Projected prizes',money(m.projected)],['Penalty paid',money(m.paid)]].map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div></details>`).join('');
$('managerFilter').innerHTML='<option value="">All managers</option>'+a.managers.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');$('monthFilter').innerHTML='<option value="">All months</option>'+a.periods.map((p,i)=>`<option value="${i}">${p.month} ${p.year}</option>`).join('');$('gwFilter').innerHTML='<option value="">All GWs</option>'+Array.from({length:a.latest},(_,i)=>`<option>${i+1}</option>`).join('');
function renderHistory(){const mid=$('managerFilter').value,gw=$('gwFilter').value,pi=$('monthFilter').value,p=pi===''?null:a.periods[+pi];const hs=a.history.filter(r=>(!mid||r.manager_id===+mid)&&(!gw||r.gw===+gw)&&(!p||(r.gw>=p.start_gw&&r.gw<=p.end_gw)));
$('historytable').innerHTML=a.history.length?table([['GW'],['Manager'],['Raw',1],['Hit',1],['Net'],['Captain',1],['Captain pts',1],['Overall total',1]],hs.map(r=>{const m=a.managers.find(m=>m.id===r.manager_id),cap=a.caps.find(c=>c.manager_id===r.manager_id&&c.gw===r.gw);return [num(r.gw),esc(m?.name),num(r.gw_points),num(r.transfer_cost),num(r.net_gw_points),esc(cap?.captain),num(cap?.captain_points),num(r.total_points)];})):'<div class="panel">GW history was not retained by the previous updater. Run the updated updater; existing snapshot remains preserved.</div>';}
for(const id of ['managerFilter','monthFilter','gwFilter'])$(id).onchange=renderHistory;renderHistory();
$('rulebody').innerHTML=`<p><b>League:</b> ${esc(a.c.name)} · ID ${a.c.id}. Rules come only from this repository’s rules_config.json.</p><p><b>Transfer hits:</b> Net GW = current total_points − previous total_points. Raw points and transfer costs are retained separately. Adjustments are included in official net.</p><p><b>Penalty:</b> Rank monthly net scores lowest first. Occupied penalty slots receive a share of the configured pool proportional to the gap from the monthly leader. For tied scores, add money for all occupied slots and divide equally across every tied manager, including those crossing the cutoff. The total pool is preserved. If all scores tie, everyone shares the pool.</p><p><b>Example:</b> Fixed occupied slot amounts ฿200 + ฿100; scores 200 / 220 / 220 → ฿200 / ฿50 / ฿50. These example amounts are not league rules.</p><p><b>Precision:</b> Equal shares are retained at full numeric precision; display rounds to 2 decimals. An indivisible satang remains a settlement rounding question rather than an arbitrary tie breaker.</p><p><b>Prizes:</b> Maximum ${num(a.c.cap)} per manager. Higher-value categories are processed first; skip ineligible managers and continue to the next eligible candidate. Prize ties use only configured tiebreaks. ${a.c.manualEqual?'Equal-value conflicts require manual review.':'Equal-value categories use configured priority.'} Pass-down now continues through all eligible candidates per the current instruction.</p><p><b>Payments:</b> Finalized = assessed after the complete month. Paid = an explicit entry in payments.json. Projected = a provisional prize or monthly result. Missing historic payment records are not proof of payment. Prize won requires a finalized prize transaction.</p><p><b>Month mapping:</b> ${a.c.schedule.map(p=>`${p.month} ${p.year}: GW${p.start_gw}–${p.end_gw}`).join(' · ')}</p>`;
$('export').onclick=()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=320+a.prizes.length*45;const ctx=canvas.getContext('2d');ctx.fillStyle='#0c1420';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#edf2f8';ctx.font='bold 32px sans-serif';ctx.fillText(a.c.name+' • GW'+a.latest,36,56);ctx.font='20px sans-serif';let y=105;for(const m of a.managers.slice(0,3)){ctx.fillText(`#${m.rank} ${m.name} • ${m.total} pts`,36,y);y+=36;}ctx.fillText(`Recorded funding ${money(paid)} / ${money(a.c.target)}`,36,y+8);y+=60;for(const p of a.prizes){ctx.fillText(`${p.label}: ${p.winner?.name||p.status} • ${money(p.amount_thb)}`,36,y);y+=42;}ctx.font='16px sans-serif';ctx.fillText('Projected prizes • Snapshot '+a.updated+' • '+a.warnings.length+' data warnings',36,canvas.height-24);const link=document.createElement('a');link.download='FPL-GW'+a.latest+'.png';link.href=canvas.toDataURL();link.click();};
}catch(e){$('warnings').innerHTML=`<div class="warning">DATA WARNING: ${esc(e.message)}</div>`;$('meta').textContent='Data could not load';$('export').disabled=true;}
})();