const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../engine.js'),c=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../rules_config.json')));
let tests=0;function test(name,f){f();tests++;console.log('PASS '+name)}const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
const rows=[{id:1,points:200},{id:2,points:220},{id:3,points:220}];
test('normal ranking and fixed slot sharing',()=>assert.deepEqual(E.sharePenalty([{points:100},{points:200},{points:300}],[200,100]).map(x=>x.amount),[200,100,0]));
test('tie at penalty boundary',()=>assert.deepEqual(E.sharePenalty(rows,[200,100]).map(x=>x.amount),[200,50,50]));
test('three managers tied across slots',()=>{const out=E.sharePenalty([{points:200},{points:200},{points:200}],[200,100]);assert.deepEqual(out.map(x=>x.amount),[100,100,100]);});
test('gap weighted pool conservation',()=>near(E.penalty(rows,2,300).reduce((s,x)=>s+x.amount,0),300));
test('all equal scores preserve pool',()=>assert.deepEqual(E.penalty([{points:20},{points:20},{points:20}],2,300).map(x=>x.amount),[100,100,100]));
test('fractional equal shares stay equal',()=>{const out=E.sharePenalty([{points:1},{points:1},{points:1}],[100]);near(out[0].amount,out[2].amount);near(out.reduce((s,x)=>s+x.amount,0),100);});
const ms=[{id:1,name:'A',rank:1,total:100,value:10,captain:90,mvp:3},{id:2,name:'B',rank:2,total:90,value:9,captain:80,mvp:2},{id:3,name:'C',rank:3,total:80,value:8,captain:70,mvp:1}];
const defs=[{key:'a',metric:'season_rank',target_rank:1,amount_thb:300},{key:'b',metric:'team_value',amount_thb:200},{key:'c',metric:'captain_points',amount_thb:100}];
test('maximum prize cap and pass down',()=>{const a=E.allocate(defs,ms,1,false);assert.deepEqual(a.map(x=>x.winner.id),[1,2,3]);assert.match(a[2].reason,/A, B/);});
test('unconfigured prize tie remains pending',()=>{const out=E.allocate([{key:'v',metric:'team_value',amount_thb:10}],ms.map(m=>({...m,value:10})),2,false);assert.equal(out[0].winner,null);});
test('league schedule is separate and spans 38 GW',()=>{const n=E.normalize(c);assert.equal(n.schedule[9].end_gw,38);assert.equal(n.prizes.length,c.league?6:7);});
const standings=ms.map(m=>({manager_id:m.id,manager:m.name,team:'T',rank:m.rank,total_points:m.total,gw_points:72,transfer_cost:4,captain_points:10,gw_mvp_wins:1,team_value:m.value}));
const history=ms.flatMap(m=>[1,2].map(g=>({manager_id:m.id,gw:g,gw_points:72,transfer_cost:4,net_gw_points:68,total_points:g*68})));
const caps=history.map(h=>({manager_id:h.manager_id,gw:h.gw,captain_points:10}));
test('monthly ranking and transfer deduction once',()=>{const a=E.build({standings,history,captain_history:caps,latest_gw:2},c);assert.equal(a.periods[0].rows[0].points,136);assert.equal(a.periods[0].rows[0].raw,144);assert.equal(a.periods[0].rows[0].hits,8);});
test('missing GW prevents finalization',()=>{const a=E.build({standings,history:history.slice(1),latest_gw:2},c);assert.equal(a.periods[0].verified,false);assert.ok(a.warnings.some(w=>w.includes('Missing Gameweek')));});
test('new month starts with correct mapping',()=>{const a=E.build({standings,history:[],latest_gw:3},c);assert.equal(a.periods[1].start_gw,3);assert.equal(a.periods[2].status,'Not started');});
test('pool and manager financial totals',()=>{const a=E.build({standings,history,captain_history:caps,latest_gw:2},c,{penalties:[{manager_id:1,amount_thb:10}],prizes:[{manager_id:1,amount_thb:50,status:'finalized'}]});near(a.money.reduce((s,m)=>s+m.assessed,0),a.periods[0].penalty_pool_thb);assert.equal(a.money[0].net,40);assert.equal(a.money[0].paid,10);});
test('saved snapshot preserved and loads',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../dashboard_data.js'),'utf8'),context);assert.equal(context.window.FPL_DASHBOARD_DATA.latest_gw,5);assert.ok(E.build(context.window.FPL_DASHBOARD_DATA,c).warnings.length);});
console.log(`${tests} tests passed`);
